### ISSUE TITLE
can't install the package on a clean conda env 

### ISSUE THREAD

**Issue by amartin211** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#14]
Here is the error I've got when trying to pip install the package:
Not to sure what to do to make it work, any suggestions please ?

Thanks 

```
Collecting aspect-based-sentiment-analysis
  ERROR: Could not find a version that satisfies the requirement aspect-based-sentiment-analysis (from versions: none)
ERROR: No matching distribution found for aspect-based-sentiment-analysis
```

**Comment by rolczynski** [comment]
hey @amartin211 - please try to use the `pip` 👍

**Comment by amartin211** [comment]
Hi, thanks for the quick reply. 
I did use pip but without any success..

**Comment by rolczynski** [comment]
Make sure that you use the python version 3.7 ☺️

**Comment by lavanaythakral** [comment]
Putting it here for reference. If you're trying to run this on Google Colab, it won't work as Colab only supports Python 2.7 and Python 3.6

**Comment by rolczynski** [comment]
now the package version 2.0 works lika a charm in Colab 😊
