### ISSUE TITLE
Pre-trained laptop classifier accuracy does not match what is stated in README

### ISSUE THREAD

**Issue by Aishwarya1023** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#15]
I replaced the domain and classifier in [test_performance.py](https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis/blob/31fb1b2e56c0e9f36b7e518edd9cc2c257d7fde2/tests/test_performance.py#L30) from restaurants to laptops and I get an **accuracy of 0.38** (the accuracy stated in the README is 0.8)

This was the code:
```
import numpy as np
import aspect_based_sentiment_analysis as absa
from aspect_based_sentiment_analysis.training import ConfusionMatrix

def test_semeval_classification_laptops():
    examples = absa.load_examples(dataset='semeval',
                                  domain='laptop',
                                  test=True)
    nlp = absa.load('absa/bert-lapt-0.1')

    metric = ConfusionMatrix(num_classes=3)
    confusion_matrix = nlp.evaluate(examples, metric, batch_size=32)
    confusion_matrix = confusion_matrix.numpy()
    accuracy = np.diagonal(confusion_matrix).sum() / confusion_matrix.sum()

    print(confusion_matrix)
    print(accuracy)
```

**Comment by rolczynski** [comment]
hey @Aishwarya1023 
thank you for this issue. In this snippet you use the post-trained language model `absa/bert-lapt-0.1`. Instead you should use this: `absa/classifier-lapt-0.1`. Please wait two weeks and the solution will be ready ☺️

**Comment by Aishwarya1023** [comment]
@rolczynski Sounds good! Please let me know here when it's ready. :) Great work btw!

**Comment by rolczynski** [comment]
It's done - check it out 😊
