### ISSUE TITLE
Unable to reach good accuracy on Training using the train_classifier.py

### ISSUE THREAD

**Issue by CVSidhant-23** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#28]
examples = absa.load_examples(domain=domain)
when I load data using the above code for laptop. I am  getting an accuracy of only 42%.
Can you please guide me on any errors I am using. 
What specifications of gpu  or memory on gpu are we expected to train on 

While training on custom data as well reaching only 35%

**Comment by rolczynski** [comment]
Please check - the performance tests [here](https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis/blob/master/tests/test_performance.py#L23) 😊 probably you load the wrong model 😅
