### ISSUE TITLE
Error in Usage

### ISSUE THREAD

**Issue by amitness** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#3]
Hi,

I cloned the repo and was trying to import the module locally. I've installed transformers as well. I'm getting this error.

Python: 3.6
![Screenshot from 2020-04-23 11-42-53](https://user-images.githubusercontent.com/8587189/80064365-9b289b00-8557-11ea-92af-c05fd3881328.png)

**Comment by rolczynski** [comment]
hey @amitness,
the first issue:tada: well, take a loot at the `environment.yml` - you should use the python version 3.7 ;) btw OrderedDict is
