### ISSUE TITLE
ValueError: Input 0 of layer classifier is incompatible with the layer: : expected min_ndim=2, found ndim=0. Full shape received: []

### ISSUE THREAD

**Issue by daniiarabdiev** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#34]
When running an example

**Comment by dh12306** [comment]
I have some error

**Comment by jedmijares** [comment]
I'm getting the same error, not sure what the problem is.

**Comment by daniiarabdiev** [comment]
I believe, I resolved the error by downgrading transformers library to 2.5

**Comment by rolczynski** [comment]
Hey folks! I have fixed this - please update to the version `2.0.2`  😊 Out of curiosity - it's transformers lib.
