### ISSUE TITLE
Read me

### ISSUE THREAD

**Issue by programmeddeath1** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#38]
In the supervising model predictions in readme in the final sentence you talk about
There are a lot of articles that illustrate various concerns why drawing conclusions about model reasoning directly from attentions might be misleading. In the article [here], we validate and analyse explanations in detail.

The article regarding the attention analysis is not hyperlinked, is it possible to share the link that would be really insightful?
Thanks for your help!

**Comment by ivankalinchuk** [comment]
Hi!

There is also a place for a hyperlink to an article about professors. Please, share the article link, it would be extremely helpful!
Here is a [header ](https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis/blob/master/README.md#pipeline-keeping-the-process-in-shape)from the readmy where a link is supposed to be: "...In the article **[here]**, we discuss in detail how the model and the professor work."

Thanks!

**Comment by rolczynski** [comment]
hey, you can find more information in my blog post [here](https://rafalrolczynski.com/2021/03/07/aspect-based-sentiment-analysis/) 😊

**Comment by ivankalinchuk** [comment]
Thank you for the response!

Regards,
