### ISSUE TITLE
Probing is not working

### ISSUE THREAD

**Issue by DarkDarkling** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#4]
Cloned repository, installed dependencies and ran **patters.ipynb** example.
It fails on the last step (absa.probing.explain) with error attached:

![Error](https://user-images.githubusercontent.com/10954307/82896670-07375e00-9f5f-11ea-9f3c-ea84a59dc19c.png)

**Comment by rolczynski** [comment]
Hey!

**Comment by DarkDarkling** [comment]
Thanks!
