### ISSUE TITLE
Update dependencies for usability

### ISSUE THREAD

**Issue by Jbollenbacher** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#42]
Hi all, 

This seems like a great library, but it's currently unusable because of the outdated dependences (tensorflow==2.2, transformers==2.5) which conflict with the versions required by other modern NLP libraries (e.g. Sentence-Transformers) that are often used in the same data pipelines.

I see you've updated the tensorflow dependency in the master github version, but have not pushed it to the pip installable version.

Please update the pip-installable library to work with current versions of tensorflow and transformers.  This would make your library much more usable and increase adoption by others.

**Comment by MoldovanAndrada** [comment]
same problem here

**Comment by rolczynski** [comment]
@Jbollenbacher could you prepare PR with such an update? 😊

**Comment by razi9126** [comment]
> ntly unusable because of the outdated dependences (tensorflow==2.2, transformers==2.5) which conflict with the versions required by other modern NLP libraries (e.g. Sentence-Transformers) that are often used in the same data pipelines.
> 
> I see you've updated the tensorflow dependency in the master github version, but have not pushed it to the pip installable version.

Same problem here. I have the M1 mac and we can only use Tensorflow 2.5 on it. The library isn't compatible with that version though. Please update the dependencies

**Comment by nnick14** [comment]
@rolczynski I prepared #55 for this. Let me know if you have any questions or need me to update/fix anything.

**Comment by rolczynski** [comment]
It's now available the upgraded version 😊
