### ISSUE TITLE
Can't install the package in anaconda!

### ISSUE THREAD

**Issue by Swapnil5101** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#52]
I wan't it to run in conda jupyter lab. I also followed steps to clone the code to create new conda env, but it didn't work. Somebody pls let me through steps to resolve the issue.

**Comment by AymenBenk** [comment]
Me too, same. Looking forward for any explanation how to get it run. 
I tried everything but there is always a Dependency problem 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-3ecd5ec3e38a> in <module>
----> 1 absa.summary(slack)
      2 absa.display(slack.review)

~\Anaconda3\envs\asba_aymen_setup\lib\site-packages\aspect_based_sentiment_analysis\plots.py in summary(example)
     64 
     65 def summary(example: PredictedExample):
---> 66     print(f'{str(example.sentiment)} for "{example.aspect}"')
     67     rounded_scores = np.round(example.scores, decimals=3)
     68     print(f'Scores (neutral/negative/positive): {rounded_scores}')

AttributeError: 'list' object has no attribute 'sentiment'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-efe3ff4940d3> in <module>
      1 # Verify the model decision
----> 2 html = absa.probing.explain(slack)
      3 display(html)

AttributeError: module 'aspect_based_sentiment_analysis' has no attribute 'probing'

**Comment by rolczynski** [comment]
It's now available the upgraded version 😊
