### ISSUE TITLE
ResolvePackageNotFound: - spacy=2.4 when using "create env create -f=environment.yml"

### ISSUE THREAD

**Issue by Awannaphasch2016** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#6]
when using "create env create -f=environment.yml" the following error is shown
ResolvePackageNotFound:
  - spacy=2.4

Do you mean 2.2.4? the lastest version is 2.2.4

**Comment by rolczynski** [comment]
uuups, thank you! I have added this by hand, the fix is on the master
