### ISSUE TITLE
Multiple tokens

### ISSUE THREAD

**Issue by samuellye98** [ScalaConsultants/Aspect-Based-Sentiment-Analysis#9]
Hi, thanks for this great library! Everything works great but I have 2 questions:

1. Is there any way to accommodate for aspects which have more than one word, e.g. task = nlp(sentence, aspects=['social media']) raises an error:

```/usr/local/lib/python3.7/site-packages/aspect_based_sentiment_analysis/probing/recognizers.py in input_validation(example, attentions, attention_grads)
    149             raise ValueError
    150         if len(example.aspect_tokens) > 1:
--> 151             raise ValueError
    152 
    153     @staticmethod

ValueError:
```

2. Are there any other properties of task.batch, such as the overall sentiment score or the words that constitute that sentiment score?

Thanks so much!

**Comment by rolczynski** [comment]
Hey @samuellye98,  
1. we will release the version 2.0 (in the next two weeks) wherein you can define an aspect by few words ☺️ 
2. this property `task.batch` is helpful when you preparing the input batch (encode the tokenized examples).
